# Generated by Django 6.1.1 on 2026-09-22 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_viagem', models.DateField(verbose_name='data da viagem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=10)),
                ('metodo_pagamento', models.CharField(choices=[('MCX', 'Multicaixa Express'), ('BALCAO', 'Pagamento na bilheteira')], default='MCX', max_length=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço total (Kz)')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('referencia_mcx', models.CharField(blank=True, max_length=50)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='routes.horario')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='código')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('USADO', 'Usado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilhete', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'bilhete',
                'verbose_name_plural': 'bilhetes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(max_length=10, verbose_name='número/código')),
                ('passageiro_nome', models.CharField(max_length=200, verbose_name='nome do passageiro')),
                ('passageiro_telefone', models.CharField(blank=True, max_length=20)),
                ('passageiro_documento', models.CharField(blank=True, max_length=50, verbose_name='BI/Passaporte')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'assento',
                'verbose_name_plural': 'assentos',
                'unique_together': {('reserva', 'numero')},
            },
        ),
    ]
