# Generated by Django 6.1.1 on 2026-09-22 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Autocarro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='matrícula')),
                ('modelo', models.CharField(max_length=100)),
                ('classe', models.CharField(choices=[('comum', 'Comum'), ('conforto', 'Conforto'), ('executivo', 'Executivo')], default='comum', max_length=20)),
                ('total_assentos', models.PositiveIntegerField(default=50, verbose_name='total de assentos')),
                ('layout_assentos', models.JSONField(blank=True, help_text='Ex: linhas de assentos 2+2, 1+2, etc.', null=True, verbose_name='layout dos assentos')),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autocarros', to='fleet.empresa')),
            ],
            options={
                'verbose_name': 'autocarro',
                'verbose_name_plural': 'autocarros',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('numero_licenca', models.CharField(blank=True, max_length=50, verbose_name='nº de licença')),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas', to='fleet.empresa')),
            ],
            options={
                'verbose_name': 'motorista',
                'verbose_name_plural': 'motoristas',
            },
        ),
    ]
