# Generated by Django 6.1.1 on 2026-09-22 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='distância (km)')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço base (Kz)')),
                ('duracao_estimada_min', models.PositiveIntegerField(default=0, verbose_name='duração estimada (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas_destino', to='tourism.provincia', verbose_name='destino')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='fleet.empresa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas_origem', to='tourism.provincia', verbose_name='origem')),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
                'ordering': ['origem__nome', 'destino__nome'],
                'unique_together': {('origem', 'destino', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('hora_saida', models.TimeField(verbose_name='hora de saída')),
                ('hora_chegada', models.TimeField(verbose_name='hora de chegada')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de inteiros 0=Seg ... 6=Dom. Vazio = todos os dias.', verbose_name='dias da semana')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço (Kz)')),
                ('is_active', models.BooleanField(default=True)),
                ('autocarro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='fleet.autocarro')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='routes.rota')),
            ],
            options={
                'verbose_name': 'horário',
                'verbose_name_plural': 'horários',
                'ordering': ['hora_saida'],
                'unique_together': {('rota', 'autocarro', 'hora_saida')},
            },
        ),
    ]
