# Generated by Django 6.1.1 on 2026-09-22 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100, verbose_name='capital')),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='provincias/')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'província',
                'verbose_name_plural': 'províncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('categoria', models.CharField(choices=[('quedas', 'Quedas'), ('parque', 'Parque Natural'), ('cultura', 'Cultura'), ('praia', 'Praia'), ('historia', 'História'), ('montanha', 'Montanha'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pontos_turisticos/')),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('preco_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço de entrada (Kz)')),
                ('horario', models.CharField(blank=True, help_text='Ex: 08:00 - 17:00', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque na home')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='tourism.provincia')),
            ],
            options={
                'verbose_name': 'ponto turístico',
                'verbose_name_plural': 'pontos turísticos',
                'ordering': ['-destaque', 'nome'],
            },
        ),
    ]
